apiVersion: batch/v1
kind: Job
metadata:
  name: dml-llm-job
  namespace: dml
spec:
  completions: 4 # should be the same as WORLD_SIZE
  parallelism: 4 # should be the same as WORLD_SIZE
  template:
    spec:
      containers:
      - name: dml-llm-container
        image: eismcc/dml-llm:latest
        imagePullPolicy: Always
        command: ["python3", "train.py"]
        ports:
        - containerPort: 8889
        env:
        - name: WORLD_SIZE
          value: "4"  # Set to the parallelism count
        - name: INPUT_PATH
          value: "/data/output"
        - name: OUTPUT_PATH
          value: "/data2/llm_output"
        - name: JOB_UUID
          value: "placeholder-for-uuid"
        resources:
          limits:
            nvidia.com/gpu: 1
        #     cpu: "2"
        #     memory: "16Gi"
        #   requests:
        #     cpu: "1"
        #     memory: "4Gi"
        volumeMounts:
        - mountPath: /data
          name: dml-data
        - mountPath: /data2
          name: dml-data-2
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: dml-data
          persistentVolumeClaim:
            claimName: dml-data-pvc
        - name: dml-data-2
          persistentVolumeClaim:
            claimName: dml-data-2-pvc
