apiVersion: batch/v1
kind: Job
metadata:
  name: dml-minst-job
  namespace: dml
spec:
  parallelism: 4 # should be the same as WORLD_SIZE
  template:
    spec:
      containers:
      - name: dml-minst-container
        image: eismcc/dml-mnist-cpu:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        env:
        - name: WORLD_SIZE
          value: "4"  # Set to the parallelism count
        resources:
          limits:
            cpu: "1"
            memory: "16Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
      restartPolicy: Never
