apiVersion: batch/v1
kind: Job
metadata:
  name: dml-tokenize-job
  namespace: dml
spec:
  completions: 16 # should be the same as WORLD_SIZE
  parallelism: 16 # should be the same as WORLD_SIZE
  template:
    spec:
      containers:
      - name: dml-tokenize-container
        image: eismcc/dml-tokenize:latest
        imagePullPolicy: Always
        command: ["python3", "dml_tokenize.py"]
        ports:
        - containerPort: 8889
        env:
        - name: WORLD_SIZE
          value: "16"  # Set to the parallelism count
        - name: INPUT_FILE_PATH
          value: "/data/input/c4.txt"
        - name: OUTPUT_PATH
          value: "/data2/output"
        - name: JOB_UUID
          value: "placeholder-for-uuid"
        - name: MAX_CHUNK_SIZE
          value: "16777216"
        resources:
          limits:
            cpu: "2"
            memory: "16Gi"
          requests:
            cpu: "1"
            memory: "4Gi"
        volumeMounts:
        - mountPath: /data
          name: dml-data
        - mountPath: /data2
          name: dml-data-2
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: dml-data
          persistentVolumeClaim:
            claimName: dml-data-pvc
        - name: dml-data-2
          persistentVolumeClaim:
            claimName: dml-data-2-pvc
