apiVersion: batch/v1
kind: Job
metadata:
  name: dml-minst-job
  namespace: dml
spec:
  completions: 4 # should be the same as WORLD_SIZE
  parallelism: 4 # should be the same as WORLD_SIZE
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: job-name
                    operator: In
                    values:
                    - dml-minst-job
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: dml-minst-container
        image: eismcc/dml-mnist-cpu:latest
        imagePullPolicy: Always
        command: ["python3", "train.py"]
        ports:
        - containerPort: 8888
        env:
        - name: WORLD_SIZE
          value: "4"  # Set to the parallelism count
        - name: LEARNING_RATE
          value: "0.001"
        - name: JOB_UUID
          value: "placeholder-for-uuid"
        # resources:
        #   limits:
        #     cpu: "128"
        #     memory: "16Gi"
        #   requests:
        #     cpu: "128"
        #     memory: "1Gi"
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
