apiVersion: batch/v1
kind: Job
metadata:
  name: dml-llm-job
  namespace: dml
spec:
  completions: 6 # should be the same as WORLD_SIZE
  parallelism: 6 # should be the same as WORLD_SIZE
  template:
    spec:
      runtimeClassName: nvidia
      containers:
      - name: dml-llm-container
        image: hyperdisk.local:9502/eismcc/dml-llm:latest
        imagePullPolicy: Always
        command: ["python3", "train.py"]
        ports:
        - containerPort: 8890
        - containerPort: 8891
        env:
        - name: WORLD_SIZE
          value: "6"  # Set to the parallelism count
        - name: INPUT_PATH
          value: "/data/output"
        - name: OUTPUT_PATH
          value: "/data2/llm_output"
        - name: JOB_UUID
          value: "placeholder-for-uuid"
        - name: PYTORCH_PORT
          value: "8890"
        - name: CONFIG_PORT
          value: "8891"
        - name: MODEL_EMBED_SIZE
          value: "256"
        - name: MODEL_SEQUENCE_LENGTH
          value: "128"
        - name: MODEL_NUM_HEADS
          value: "2"
        - name: MODEL_NUM_LAYERS
          value: "2"
        - name: MODEL_FORWARD_EXPANSION
          value: "4"
        - name: TRAIN_LR
          value: "0.0001"
        - name: TRAIN_BATCH_SIZE
          value: "128"
        - name: TRAIN_NUM_EPOCHS
          value: "100"
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        #     cpu: "2"
        #     memory: "16Gi"
        #   requests:
        #     cpu: "1"
        #     memory: "4Gi"
        volumeMounts:
        - mountPath: /data
          name: dml-data
        - mountPath: /data2
          name: dml-data-2
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: dml-data
          persistentVolumeClaim:
            claimName: dml-data-pvc
        - name: dml-data-2
          persistentVolumeClaim:
            claimName: dml-data-2-pvc
